### ISSUE TITLE
No connection to broker

### ISSUE THREAD

**Issue by Bladeacus** [Nick-Adams-AU/5500SHAC-Cbus2MQTT#1]
Hi, 

I've installed the resident scripts and event script as per the instructions, but can't seem to get a connection coming through on my MQTT broker (mosquitto addon in Hassio). 

I've successfully connected to the broker using MQTT Explorer on my PC with the same credentials that I've used in the resident scripts, so I know the credentials are correct.

Wasn't sure if I was messing up the mqtt_broker line so these are the combinations I've tried: "IPaddress"    , "IPAddress:1883" , "http://IPaddress"

Not sure where I'm getting it wrong? 

Thanks in advance

**Comment by Nick-Adams-AU** [comment]
Hey @Bladeacus.
Here's the relevant mosquitto API documentation for that parameter:

https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_connect

It should be either a hostname or an IP address. For example, mine is set to "mqtt.MYDOMAIN.com". Including the port number ("IPAddress:1883") or http protocol ("http://IPaddress") will not work. 

Does the SHAC script error log show any more information?

**Comment by Nick-Adams-AU** [comment]
How'd you go @Bladeacus? Did you manage to grab the error logs?

**Comment by Bladeacus** [comment]
Thanks for the response. Sorry for the delay.

I managed to get the SHAC to open the connection to my MQTT server by slightly modifying the mosquitto connection (pretty much just removing the variables created for login and passing directly), although this is the error now on the mqtt2cbus script:

__mqtt2cbus 05.07.2020 13:07:10_
Resident script:74: attempt to call global 'round' (a nil value)
stack traceback:
 Resident script:74: in function <Resident script:27>
 [C]: in function 'loop_forever'_

Here's the script:

```
mqtt_read_topic = 'cbus/read/'
mqtt_write_topic = 'cbus/write/'

-- load mqtt module
mqtt = require("mosquitto")

-- create new mqtt client
client = mqtt.new()

log("created MQTT client", client)

client.ON_CONNECT = function()
  log("MQTT connected - receive")
  local mid = client:subscribe(mqtt_write_topic, 2)
end

client.ON_MESSAGE = function(mid, topic, payload)

  log(topic, payload)
  
  parts = string.split(topic, "/")

  if not parts[6] then
    
    log('MQTT error', 'Invalid message format')
    
  elseif parts[6] == "getall" then
    
    datatable = grp.all()
    for key,value in pairs(datatable) do
      dataparts = string.split(value.address, "/")
		  network = tonumber(dataparts[1])
		  app = tonumber(dataparts[2])
      group = tonumber(dataparts[3])
      if app == tonumber(parts[4]) and group ~= 0 then
		    level = tonumber(value.data)
    		state = (level ~= 0) and "ON" or "OFF"
        log(parts[3], app, group, state, level)
        client:publish(mqtt_read_topic .. parts[3] .. "/" .. app .. "/" .. group .. "/state", state, 1, true)
    		client:publish(mqtt_read_topic .. parts[3] .. "/" .. app .. "/" .. group .. "/level", level, 1, true)
  		end	
  	end
    log('Done')
  elseif parts[6] == "switch" then
    
    if payload == "ON" then
			SetCBusLevel(0, parts[4], parts[5], 255, 0)
    elseif payload == "OFF" then
      SetCBusLevel(0, parts[4], parts[5], 0, 0)
    end
    
  elseif parts[6] == "measurement" then

    SetCBusMeasurement(0, parts[4], parts[5], (payload / 10), 0)
    
  elseif parts[6] == "ramp" then

    if payload == "ON" then
			SetCBusLevel(0, parts[4], parts[5], 255)
    elseif payload == "OFF" then
      SetCBusLevel(0, parts[4], parts[5], 0)
    else
      ramp = string.split(payload, ",")
      num = round(ramp[1])
      if num and num < 256 then
        if ramp[2] ~= nil and ramp[2] > 1 then
	        SetCBusLevel(0, parts[4], parts[5], num, ramp[2])
        else
	        SetCBusLevel(0, parts[4], parts[5], num, 0)
        end
      end
    end
    
  end
  
end

broker = '192.168.2.35'
client:login_set("user","password")
client:connect(broker)
client:loop_forever()
```

**Comment by Nick-Adams-AU** [comment]
In the log, can you please let me know what command is being sent to trigger this error? 

I suspect the MQTT payload is malformed and should either be handled better by the script or ignored.

**Comment by Bladeacus** [comment]
So I've played around a bit and noticed that the cbus2mqtt part of the script seemed to be working fine..
Anytime I manually set an object value from the SHAC, the lighting entity in HASS updates correctly.

So I then tried to send a command from HASS using the mqtt2cbus component. Triggering this from my mqtt light entity would work once (as an OFF for example) and then refuse to turn ON again from the same entity button. 
This would then reproduce the error in the SHAC that I posted above.

`mqtt2cbusoriginal 07.07.2020 20:28:24
Resident script:74: attempt to call global 'round' (a nil value)
stack traceback:
 Resident script:74: in function <Resident script:27>
 [C]: in function 'loop_forever'`

I then bypassed this entity button and tried to trigger a group address directly by manually writing the MQTT topic/payload in HASS developer tools section. Success!

It seems like the issue that I'm experiencing is in the way I've configured my home assistant light entity.

`- platform: mqtt
  name: Hallway Lights
  state_topic: "cbus/read/254/56/21/state"
  command_topic: "cbus/write/254/56/21/switch"
  brightness_state_topic: "cbus/write/254/56/21/ramp"
  brightness_command_topic: "cbus/read/254/56/21/level"
  brightness_command_topic: "cbus/write/254/56/21/ramp"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 2
  brightness_scale: 100
  on_command_type: "brightness"`

The above configuration is something I had implemented on a previous install when running cgate2web.

Assuming that the on_command_type of "brightness" is the issue here.

**Comment by Nick-Adams-AU** [comment]
Great to hear that things work well via direct MQTT.

I think your entity config is a bit off. In particular, the brightness_state_topic should refer to the level not the ramp. You also have a duplicate brightness_command_topic.

Here's what I use:

```yaml
  - platform: mqtt
    name: Pantry benches
    state_topic: 'cbus/read/254/56/2/state'
    command_topic: 'cbus/write/254/56/2/switch'
    brightness_state_topic: 'cbus/read/254/56/2/level'
    brightness_command_topic: 'cbus/write/254/56/2/ramp'
    payload_on: 'ON'
    payload_off: 'OFF'
    on_command_type: 'brightness'
```
If this works for you, I'll update the documentation to provide examples.

**Comment by Nick-Adams-AU** [comment]
Did the updated HA config work for you @Bladeacus?

**Comment by Bladeacus** [comment]
Hi @Nick-Adams-AU , thanks for following up - I haven't applied your example yet, my previous configuration was setup for the cgate2web integration and was working for that.

I'll give it a go on your project setup and see how it runs with your updated config and let you know.

Thanks again

**Comment by Nick-Adams-AU** [comment]
I'll close this off now. Feel free to get back to me if you need more help.
