### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by SNOWGUM** [Nick-Adams-AU/5500SHAC-Cbus2MQTT#3]
Hey, I'm not sure what I'm doing wrong but I've been trying this for a few days now and I'm not making any progress. 
I followed your documentation step by step exactly as said. Below are screenshots of what I've got.

![Screen Shot 2022-03-23 at 9 09 44 am](https://user-images.githubusercontent.com/16774291/159584648-6a2cabc6-7f3a-40ac-916d-79341bc9c3d7.png)
![Screen Shot 2022-03-23 at 9 10 14 am](https://user-images.githubusercontent.com/16774291/159584713-0152bb3d-736e-41ae-84af-5c3c84007e44.png)

When I switch either the 2 lights, about 5 seconds later they'll switch off again...
![Screen Shot 2022-03-23 at 9 10 29 am](https://user-images.githubusercontent.com/16774291/159584740-0af23b81-6d2c-4f42-bc68-a8d1dcd197fb.png)

This is my configuration.yaml, I'm not sure if this is the right place to have put this... 
<img width="440" alt="Screen Shot 2022-03-23 at 9 11 05 am" src="https://user-images.githubusercontent.com/16774291/159584800-0148820f-b8f2-48d1-9466-3728a0408418.png">

![Screen Shot 2022-03-23 at 9 13 43 am](https://user-images.githubusercontent.com/16774291/159585092-16fb84bc-49c6-4c38-9a03-07e3709f97b6.png)
![Screen Shot 2022-03-23 at 9 14 04 am](https://user-images.githubusercontent.com/16774291/159585131-a0040730-5fec-4d51-8817-c3a0c0e0feea.png)

I know this is just a dump of information, but if you can see anything wrong please let me know, I really like the idea of using shac's instead of CNI's with C-Gate. Any help would be greatly appreciated. Thanks

**Comment by Nick-Adams-AU** [comment]
Thanks for reaching out. A couple of questions:

1/ When you do switch the lights on via HA, does it actually turn on? I wanted to check if you have one direction working OK but not the other....or...if everything is buggered.

2/ Do you see anything in the SHAC logs? There's an event log and error log. If you can post a screenshot or content of both logs please.

**Comment by ZEi20T** [comment]
i cant get the script working with the built-in MQTT broker with HomeAssistant. im using mosquitto in a docker on another machine and it works fine. try that first, it might be the broker

**Comment by Nick-Adams-AU** [comment]
@ZEi20T You are right...there is an incompatibility between the SHAC MQTT implementation and the internal broker however it looks like @SNOWGUM is using an external broker.

**Comment by SNOWGUM** [comment]
Wow, that was fast. Yeah, I installed the Mosquito broker in Home Assistant and have that running bit I've never seen a connection log. I've connected with an Mqqtt client on my computer and that's worked fine. 

Regarding when I switch lights, I'm not seeing anything really strange. Below is a photo of my shack logs. 
I have no error logs. 
![Screen Shot 2022-03-23 at 9 35 51 am](https://user-images.githubusercontent.com/16774291/159587661-fa20d70a-cec7-4af0-8255-88b3bd683492.png)

**Comment by Nick-Adams-AU** [comment]
So it looks like the first time it connected was about 40 mins ago - the last two lines (connected - send/receive). Are you sure the SHAC can talk to the MQTT broker and that you are using the correct IP/port combination?

> Regarding when I switch lights

Do the lights actually switch though?!

**Comment by SNOWGUM** [comment]
No, they don't I haven't seen anything switch. 

and my Home Assistant is sitting at 192.168.69.17, the MQTT port is default 1883, I've tried changing the hostname in the SHAC to include and exclude the port number but neither give me any luck

**Comment by SNOWGUM** [comment]
I must be doing something really really wrong haha, I'm just not sure how or what.

**Comment by Nick-Adams-AU** [comment]
Can you confirm that:

- You've disabled the internal HA MQTT broker; and 
- Then connected HA to your external broker?

You should then be able to go into the MQTT config in HA to manually subscribe and send MQTT packets to test the functionality. Try doing both of the below and let me know what you get. Try turning the lights off using an EDLT or switch and see if the update is published. If you get nothing, check the connection between the SHAC and HA.

Listen to a topic
Topic: cbus/read/254/56/1/state

Publish a packet:
Topic: cbus/write/254/56/1/switch
Payload: on

**Comment by SNOWGUM** [comment]
I'm not sure how to disable the existing HA MQTT Broker. 

And I'm not getting any communication between the SHAC or HA
<img width="658" alt="Screen Shot 2022-03-23 at 12 42 20 pm" src="https://user-images.githubusercontent.com/16774291/159605110-79d72602-34c1-4368-9240-c3e1c9f3fa36.png">

**Comment by Nick-Adams-AU** [comment]
I just noticed that the internal MQTT broker has been deprecated for almost a couple of years now. I hadn't noticed as I always used an external broker.

Double check the MQTT IP and port settings in the SHAC scripts and that they can talk (i.e. no firewall issues).

You can also try listening to the below topic and flick some lights to see if the updates are pushed although I suspect you won't see anything as the SHAC isn't connected to MQTT:

cbus/read/#

**Comment by SNOWGUM** [comment]
Below are some screenshots, the HA host's firewall is disabled and I have no restrictions within my local network. 


<img width="477" alt="Screen Shot 2022-03-23 at 12 55 23 pm" src="https://user-images.githubusercontent.com/16774291/159606434-334d2a4b-befe-4c98-b70f-b8a9a594532d.png">
<img width="272" alt="Screen Shot 2022-03-23 at 12 57 19 pm" src="https://user-images.githubusercontent.com/16774291/159606625-38704877-f885-4992-9b49-2faa317f4549.png">

**Comment by Nick-Adams-AU** [comment]
Can you connect to the MQTT broker using telnet or nc from another device on the same network?

**Comment by pbyrne-ms** [comment]
Hi - if you have a brand new install of Mosquitto on a separate/external box, it might be worth checking it's conf file, as recent changes to the mosquitto package changed the default install to not accept anonymous connections (probably this is fine for you) but it also no longer allows access from external clients by default - i.e. your SHAC. 

Lots of ways to do this, but on my Broker system (Raspberry PI) I use:
`sudo nano /etc/mosquitto/mosquitto.conf `

then make sure the file contains the line
`listener 1883`

enter this line/text if it's not there already. Ctrl+X to save and exit.

Reload & Restart Mosquitto
`sudo systemctl daemon-reload && sudo systemctl restart mosquitto.service`

it might be no harm to also do a reboot, but usually the above is enough...

Not sure if this is your actual issue, but worth checking just to rule it out at least...

**Comment by SNOWGUM** [comment]
@pbyrne-ms 
The Mosquito Broker is within Home Assistant, I've tried adding `allow_anonymous: true listener: 1883` to the config, not sure if they do anything but worth a shot.
@Nick-Adams-AU I'm going to try your suggestion now.

**Comment by SNOWGUM** [comment]
So I've connected to the MQTT server on my computer, and I can see Cbus messages when I switch the HA light. When I send `cbus/read/254/56/2/state` I get status changes on HA. So the MQTT Server looks to be working just the SHAC isn't communicating. 


<img width="1038" alt="Screen Shot 2022-03-24 at 10 41 14 am" src="https://user-images.githubusercontent.com/16774291/159814138-88217f0a-d34a-40a3-b98a-e92cba86893e.png">

**Comment by Nick-Adams-AU** [comment]
Is 192.168.69.32 the IP for the SHAC?

Can you confirm the FW version of the SHAC too please? It's in the bottom left hand corner when you log in.

**Comment by Nick-Adams-AU** [comment]
Another user has reported issues with the HA add-on broker. Can I request that you try to use an external broker (such as https://test.mosquitto.org/) and see if that works?

I need to do more investigation as to why the SHAC's MQTT implementation is so flaky.

**Comment by redstorm1** [comment]
> I need to do more investigation as to why the SHAC's MQTT implementation is so flaky.

The fix for the default HA MQTT implementation is to set a client id in the resident LUA scripts. Their is an issue when a clientid contains a "/" which the LUA scripts auto generated client id contain. I fixed this last night by adding a client id to the  two resident scripts and I am using the default HA eclipse MQTT addon.

Added a clientid variable and used when creating the client.

cbus2mqtt.lua
```
clientid = 'cbus2mqtt'
-- create new mqtt client
client = mqtt.new(clientid)
```
mqtt2cbus.lua
```
clientid = 'mqtt2cbus'
-- create new mqtt client
client = mqtt.new(clientid)
```
I used a different client id for each of the resident scripts.

Edit: Added Versions and MQTT config
SHAC
Version: 1.6.0, hw v1.0
Home Assistant MQTT 6.0.1
MQTT Config
`certfile: fullchain.pem
customize:
  active: false
  folder: mosquitto
keyfile: privkey.pem
logins: []
require_certificate: false`

**Comment by SNOWGUM** [comment]
Sorry for the inactivity, My SHAC version @Nick-Adams-AU  is 1.6.0. 

I've just tried what @redstorm1 suggested and it hasn't seemed to make a difference. 

I'm currently out of town with work so I'm using remote desktop, but I'll make sure to dive a little deeper once I get home. 

Thanks for all the help.

**Comment by redstorm1** [comment]
In Home Assistant make sure the the SHAC scripts have registered with a client ID that does not contain a "/" or all events get filtered out.

If you go to Supervisor MQTT and the log  you can see the connection there.
Should look like this.
1648505006: New client connected from 192.168.2.4 as cbus2mqtt (p1, c1, k60, u'hauser').
1648505006: New client connected from 192.168.2.4 as mqtt2cbus (p1, c1, k60, u'hauser').
if you get something like this
New client connected from 192.168.2.4 as mosq/bv]4EmKK1Qx9@^82^R (p1, c1, k60, u'hauser').
It means your changes have not taken effect, deactivate and activate the resident scripts to force it to re connect.

**Comment by Nick-Adams-AU** [comment]
> The fix for the default HA MQTT implementation is to set a client id in the resident LUA scripts. Their is an issue when a clientid contains a "/" which the LUA scripts auto generated client id contain. I fixed this last night by adding a client id to the two resident scripts and I am using the default HA eclipse MQTT addon.

Thanks for this! Great find. Fixed in #4.

**Comment by Nick-Adams-AU** [comment]
Hey @SNOWGUM ...did the changes in #4 help at all?

**Comment by ZEi20T** [comment]
Thank you all for the updates!

I got back from my holiday and modified the scripts and it works with the built-in MQTT broker with HA!

**Comment by Nick-Adams-AU** [comment]
Thanks for your patience and persistence! Glad it works.

**Comment by SNOWGUM** [comment]
So sorry @Nick-Adams-AU I went off the grid a little there. This works perfectly thanks so much for your work and thanks for all your help. Much appreciated.
