### ISSUE TITLE
Measurement application

### ISSUE THREAD

**Issue by redstorm1** [Nick-Adams-AU/5500SHAC-Cbus2MQTT#6]
Creating a measurement app on the SHAC with Keyword all is not published to MQTT vis versa publishing a measurement also does not update the SHAC group address for the measurement application.

If i manually set a value in the SHAC and monitor MQTT it publishes the below.
Message 14 received on cbus/read/254/228/0/level at 12:40 PM:
0
QoS: 0 - Retain: false
Message 13 received on cbus/read/254/228/0/state at 12:40 PM:
OFF

No measurement is published.

Goal is to be able to inject an external non CBUS temp into the SHAC.

Could be that the measurement app has potentially 7 parts too it as it also includes a channel number.
0/228/0/0/measurement ??

 parts = string.split(topic, "/")

  if not parts[6] then
    
    log('MQTT error', 'Invalid message format')

**Comment by Nick-Adams-AU** [comment]
> Goal is to be able to inject an external non CBUS temp into the SHAC.

So this use-case should work as I have Home Assistant push Zigbee temperatures to CBus to be displayed on an EDLT.

That said, you seem to be testing pushing CBus measurements back to MQTT? i.e. the other way around. Is that what you want? I haven't tested this reverse functionality before.

**Comment by redstorm1** [comment]
Thats exactly what i want to do, maybe i dont have my publishing topic correct. 
I configured a measurement address in hte SHAC which is displayed as 0/228/0/0

Tried publishing to
cbus/write/254/228/0/measurement
but the value in the SHAC does not update.

So i reversed it to see what topic the SHAC would publish too if i set a value in the SHAC.

If you have an example topic string its probably all it is.
My Temps will be from ESPHome devices but essentially the same as what your doing and displaying on a eDLT

**Comment by redstorm1** [comment]
created another one that had group address 1 and channel 1 incase it was some weirdness with channel 0
Logging in the SHAC reports the value i sent being 250 for 25C.

* arg: 1
  * string: cbus/write/254/228/1/measurement
* arg: 2
  * string: 250

**Comment by Nick-Adams-AU** [comment]
That's correct - CBus measurement values are 10x the reported value. So 25.5deg/c is 255. 

Looks good then?

**Comment by redstorm1** [comment]
Figured it out, the Part[4] you have to use the name you configured.

cbus/write/254/Temp/1/measurement

In my case "Temp" then it updates in the SHAC

maybe just a doc update in the readme...

**Comment by Nick-Adams-AU** [comment]
Hrmm...that's weird that it works like that. Looking at the documentation it does seem like that will work either as a name or a group number.

You happy to close this?

**Comment by redstorm1** [comment]
All good to close Thanks for the quick reply.
