### ISSUE TITLE
Potential Issue in mqtt2cbus.lua when sending a ramp

### ISSUE THREAD

**Issue by pbyrne-ms** [Nick-Adams-AU/5500SHAC-Cbus2MQTT#7]
Hi,
In mqtt2cbus.lua, at about line 68 ish (as of 15-Apr-2022 ), there is a quite nice un-documented feature that handles situations where a user might send an ON or OFF command to the ramp function, where it process this and sends 0 or 255 as appropriate, instead. 
It's very possible I am misunderstanding the intent here, but I did find that I had to add "**_,0_**" to the end of the lines, to force the ramp rate to 0. The function wouldn't work without it and did noting...

This is what I did to fix it on my install:
```
    if payload == "ON" then
			SetCBusLevel(0, parts[4], parts[5], 255, 0)
    elseif payload == "OFF" then
      SetCBusLevel(0, parts[4], parts[5], 0, 0)
	  
    -- ...and so on.....
```
Just said I would mention it...feel free to delete/close if I missed the intended use...	  

Love your scripts btw, thanks so much for posting them, I've been using them for ages!

**Comment by Nick-Adams-AU** [comment]
Thanks for your report and you are absolutely correct. The way I have this integrated with Home Assistant for my use-case doesn't touch this code path but with manual testing, it is indeed a bug.

I'll drop a patch now.
