### ISSUE TITLE
Saw your work and thought I'd share

### ISSUE THREAD

**Issue by autoSteve** [Nick-Adams-AU/5500SHAC-Cbus2MQTT#9]
Hey Nick.

Saw your work integrating CBus with Home Assistant, and thought I'd share my project. It adds HA discovery add/change/delete, trigger groups, binary sensors, buttons and a lot more including CBus integration with Philips Hue via hue2mqtt.

https://github.com/autoSteve/acMqtt

Cheers.

**Comment by Nick-Adams-AU** [comment]
Hey Steve. Very, very nice work! Much more polished than my solution. Thanks for contributing it publicly.

Do you mind if I drop a link to your project in my README?

**Comment by autoSteve** [comment]
I'd be honoured.

**Comment by Nick-Adams-AU** [comment]
Done! Thanks again.
